### ISSUE TITLE
[BUG] - ImportError: DLL load failed while importing _rust: The specified program could not be found。

### ISSUE THREAD

**Issue by moran0710** [paramiko/paramiko#2360] opened 2024-02-09 15:20 UTC
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH, Something else

### What version(s) of paramiko are you using?

3.4.0

### What version(s) of Python are you using?

3.9.0

### What operating system and version are you using?

Windows 11

### Expected/desired behavior

Paramiko be successfully imported

正确导入paramiko

### Actual behavior

raise  ImportError: DLL load failed while importing _rust: The specified program could not be found。

抛出异常ImportError: DLL load failed while importing _rust: 找不到指定的程序。

### How to reproduce

Generate a virtualenv virtual environment
Install paramiko afterward
Run it after importing paramiko
Abnormalities appear

生成一个virtualenv虚拟环境
之后安装paramiko
导入paramiko后运行
异常出现

Minimal instance:
`import paramiko`

最小实例：
`import paramiko`

### Anything else?

In the issue of other projects, I found a solution that works for me
After uninstalling cryptography, specify cryptography ==3.4.7
After trying to run it again, the exception becomes ImportError: DLL load failed while importing _bcrypt: The specified program could not be found.
Uninstall bcrypt after that, specifying that the installation version is bcrypt==4.1.1
Problem solving

在其他项目的issue里面，找到了适用于我的解决方案
卸载cryptography之后指定版本为cryptography==3.4.7
之后再次尝试运行，异常变成了ImportError: DLL load failed while importing _bcrypt: 找不到指定的程序。
在之后卸载bcrypt，指定安装版本为bcrypt==4.1.1
问题解决

Also, I don't speak English very well, so please forgive me for using the bing translation here

另外，我英语不太好，所以这里使用了bing翻译，请见谅

**Comment by jun66j5** [comment] 2024-02-09 15:38
That is an issue of pyca/cryptography, not paramiko. Instead, please search the same and report it to pyca/cryptography project.

**Comment by bskinn** [comment] 2024-02-09 16:07
No, please don't delete it. It'll help others who might come with the same problem understand the situation.

**Comment by moran0710** [comment] 2024-02-09 16:27
okay i know ,thanks
i will report this but to the right place

**Comment by jun66j5** [comment] 2024-02-09 17:34
The same issue has been reported at https://github.com/pyca/cryptography/issues/10300. Also, according to https://github.com/pyca/cryptography/issues/10300#issuecomment-1921560316, the issue is no longer appeared since Python 3.9.2.

I just tried with Python 3.9.0 and 3.9.13 in my environment. I confirmed it is reproduced with Python 3.9.0 and not reproduced with Python 3.9.13.

I think we cloud close this issue.

### pip list
```
Package      Version
------------ -------
bcrypt       4.1.2
cffi         1.16.0
cryptography 42.0.2
paramiko     3.4.0
pip          22.0.4
pycparser    2.21
PyNaCl       1.5.0
setuptools   58.1.0
```

### Python 3.9.0
```
C> C:\usr\tmp\venv-py3.9.0\Scripts\python -c "import paramiko; print(paramiko.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\usr\tmp\venv-py3.9.0\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "C:\usr\tmp\venv-py3.9.0\lib\site-packages\paramiko\transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "C:\usr\tmp\venv-py3.9.0\lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\usr\tmp\venv-py3.9.0\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "C:\usr\tmp\venv-py3.9.0\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
```

### Python 3.9.13
```
C> C:\usr\tmp\venv-py3.9.13\Scripts\python -c "import paramiko; print(paramiko.__version__)"
3.4.0
```

**Comment by bskinn** [comment] 2024-02-10 00:06
Agreed, it seems clear that this has been resolved by the `cryptography` dependency.

**Closed by bskinn** 2024-02-10 00:06 UTC
Labels: Support
