### ISSUE TITLE
AttributeError can be thrown on connect

### ISSUE THREAD

**Issue by ovianao** [paramiko/paramiko#2117] opened 2022-09-21 14:21 UTC
This was seen on Paramiko 2.11.0

08:13:45 c:\jenkins\shiningpanda\jobs\aa927fcb\virtualenvs\1e8a6926\lib\site-packages\paramiko\client.py:446
08:13:45 > passphrase,
08:13:45 c:\jenkins\shiningpanda\jobs\aa927fcb\virtualenvs\1e8a6926\lib\site-packages\paramiko\client.py:677
08:13:45 > key_filename, pkey_class, passphrase
08:13:45 c:\jenkins\shiningpanda\jobs\aa927fcb\virtualenvs\1e8a6926\lib\site-packages\paramiko\client.py:593
08:13:45 > self._log(DEBUG, msg)
08:13:45 c:\jenkins\shiningpanda\jobs\aa927fcb\virtualenvs\1e8a6926\lib\site-packages\paramiko\client.py:768
08:13:45 > self._transport._log(level, msg)
08:13:45 E AttributeError: 'NoneType' object has no attribute '_log'

**Comment by jun66j5** [comment] 2022-09-21 14:24
Please provide your script. Your script should have root cause.

**Comment by ovianao** [comment] 2022-09-26 19:22
@jun66j5, my script is internal to the company; I can't provide it verbatim.
This was a one time occurrence, though I suspect it's reproducible.  I'll attempt and provide a custom script.

**Comment by chengyechun** [comment] 2022-10-14 01:40
No value is assigned to the port of the SSHClient,It should look like this.
trans = paramiko.Transport((server,port))
trans.connect(username=user, password=pw)
ssh = paramiko.SSHClient()
ssh._transport = trans

**Comment by jun66j5** [comment] 2022-10-14 01:49
> ssh._transport = trans

That's wrong programming. You should use [SSHClient.connect](https://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient.connect) if you want to use SSHClient.

**Comment by ovianao** [comment] 2022-10-14 21:10
For some reason the lines #s in the stack trace are a bit off, but:

.. self._transport is assigned here (during connect):
https://github.com/paramiko/paramiko/blob/50d33223f9ec9e308a3fda519b36f78be859c4bc/paramiko/client.py#L370

.. when we get here (before connect returns), self._transport is None:
https://github.com/paramiko/paramiko/blob/50d33223f9ec9e308a3fda519b36f78be859c4bc/paramiko/client.py#L435

.. how does that happen?
https://github.com/paramiko/paramiko/blob/50d33223f9ec9e308a3fda519b36f78be859c4bc/paramiko/client.py#L464

.. the only thing I can think of is that somehow I have a second thread calling close() on the client, before connect() is finished, understanding full well that Paramiko is not thread-safe.

Sure enough, after taking a look through our code, we do have a second thread that is operating on the same SSHClient instance.  There is the possibility of calling close(), while our main thread is in the middle of connect().

Thanks everyone, and I'm sorry for the false alarm.

**Closed** 2022-10-14 21:10 UTC
Labels: Support
