### ISSUE TITLE
TypeError: __str__ returned non-string (type bytes)

### ISSUE THREAD

**Issue by franciscouzo** [paramiko/paramiko#853] opened 2016-11-26 20:33 UTC
When using Python 3, `str(key)` throws a `TypeError` exception:

```
>>> key = paramiko.RSAKey(filename="id_rsa_paramiko")
>>> str(key)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __str__ returned non-string (type bytes)
```

I only tried with `RSAKey`, but looking at the source code it looks like all `PKey` subclasses have the same problem.

**Comment by arpit1997** [comment] 2016-11-29 05:50
It seems like a small mistake in the code to me:
```
    def asbytes(self):
        m = Message()
        m.add_string('ssh-rsa')
        m.add_mpint(self.public_numbers.e)
        m.add_mpint(self.public_numbers.n)
        return m.asbytes()

    def __str__(self):
        return self.asbytes()

```
here it returns bytes instead of strings even in `__str__` function. It seems odd to me 
:small_airplane: :smile_cat:

**Comment by bitprophet** [comment] 2016-11-29 23:39
Yea that sounds like something which was only tested under Python 2, wonder if our test suite covers that particular method. Thanks for the report!

**Comment by bitprophet** [comment] 2017-02-21 01:58
Side note, I've also always wondered why `asbytes` is even considered a useful `__str__` for a key at all. Why not its public key text, or even better, a standard colon-separated hex-y fingerprint? But that's for another ticket because changing it _that_ much is backwards incompatible...

**Comment by bitprophet** [comment] 2017-02-21 02:10
Also, looking, this is actually a dupe of #484. This ticket has more in it now, so I'll roll it in here instead of vice versa.

**Comment by bitprophet** [comment] 2017-02-21 02:34
I have a test that proves the issue, so there's that.

Of course, now we're back in the usual problem space of "...so how _should_ we string these bytes?". I squinted at this for way too long before realizing that if we want to be backwards compat we just...`return str(self.asbytes())`. I.e. the issue was the 'protocol violation' of a `__str__` returning bytes - not the actual, literal attempt to turn the bytes object into a (Unicode) string. As long as nobody explicitly tries `.decode()` on the bytes (which won't work) things appear happy.

Also, #726 is the ticket for "let's make this return something more useful in 3.0". I'll note that the behavior of this method is unchanged since 2003.

**Comment by bitprophet** [comment] 2017-02-21 02:46
Hm nope, I'm still dumb. That's getting us the string of the repr for whatever reason (i.e. `"b'\x00\x00...'"` instead of `'\x00\x00...'`). Definitely something obvious I'm missing, will keep poking and feeling this impostor syndrome.

**Comment by bitprophet** [comment] 2017-02-21 03:44
Think we have only two reasonable options:

- Go for literal equality between Python 2 and Python 3, meaning a string mixing backslash-escape hex and ascii or utf8 string data. This is what I was trying to get (mostly because I wanted to compare to a constant string value in the test file) but it seems unrealistic without doing dumb shit.
- Go for logical equivalence, meaning effectively, `repr(key.asbytes())`. These _do not compare equally_ between the interpreters because the Python 3 edition has a leading `b`. But as it stands the return value of this method isn't intended to be any sort of comparable value, and anyways, we're talking two different interpreters here. The only thing that would unify them is our test suite, and I can just plug in two different values instead, I guess.

It's tempting to just say "fuckit, this type change is allowable in a feature release", bump this to e.g 1.9/2.2, and do #726 early...sigh. (OTOH I'm trying to get away from pre-2.0 feature releases now, so...eh.)

**Comment by bitprophet** [comment] 2017-02-21 03:57
Well, `str(key.asbytes())` actually...is still the right solution here, insofar as it means both values end up printing largely the same (whereas `repr` behaves differently on Python 2 than on 3. Because of course it does.)

**Comment by bitprophet** [comment] 2017-02-21 04:06
Hrm that still feels dumb because it's still quite different from the old Python 2 behavior :(

Poked some more, and interestingly, `self.asbytes().decode('utf8', errors='ignore')` results in an identical output _when printed_ even though the _repr()s of the resulting strings differ in spots_. I don't entirely grok why that would be but I'm kinda past caring at this point, again given how pointless this all is for anything serious.

So I may just go for that for now.

**Closed** 2017-02-21 05:04 UTC
Labels: Bug, Needs patch

**Comment by bitprophet** [comment] 2017-02-21 05:05
Test happy, manual fuckery happy, Travis-CI happy, we are now exiting the rabbit hole.

**Comment by franciscouzo** [comment] 2017-03-22 03:51
Just a minor nitpick, but it looks like the fix was applied only to `RSAKey`, I think it would be better to move the `__str__` implementation to `PKey`, so all `Pkey` subclasses can benefit from it.

**Comment by bitprophet** [comment] 2017-03-22 18:50
Yea the structure of the key classes is definitely not how I would have done it and there's at least some cleanup that wants doing. We'll get there sometime. Other things are currently higher priority.

**Comment by jlost** [comment] 2021-03-16 16:55
This problem still exists.

**Comment by M0NsTeRRR** [comment] 2021-04-08 19:26
> 
> 
> This problem still exists.

Same issue, can you reopen the issue ?
