### ISSUE TITLE
Big speed problem using paramiko.SFTPClient

### ISSUE THREAD

**Issue by damiendube** [paramiko/paramiko#60] opened 2012-01-31 18:36 UTC
I am using paramiko to send big files between two RHEL5.5 servers and I am seeing a BIG speed gap between paramilo and scp (or sftp).

Here is the code I run in python

<code>
t = paramiko.Transport((hostname, 22))
t.connect(username=username, password=password, hostkey=hostkey)
sftp = paramiko.SFTPClient.from_transport(t)
sftp.put(in_file, out_file)
</code>

With this code I get about 6MB/s on a gigabyte connexion.

I also tried using compression 
<code>
t.use_compression()
</code>
I was able to get to 11MB/s

On the same system, scp will reach at least 50MB/s !

Is there something I could tweak to get better speed results?

**Comment by Dreamsorcerer** [comment] 2015-07-17 16:14
I'm encountering serious performance issues too. Downloading a directory of 313 items totalling 4.2 MB through my file browser takes me about 10 seconds, with paramiko it takes in the region of an hour.

**Comment by Dreamsorcerer** [comment] 2015-07-17 16:52
Printing out the files as they are downloaded, I can see that it has downloaded a bunch of text files in the region of 60KB each without a problem, but when it gets to a .png that is only 5.5KB it hangs for atleast several minutes.

**Comment by Dreamsorcerer** [comment] 2015-07-17 16:53
Oh, there are other .png's before that which it has also downloaded fine. But, it always gets stuck at the same file.

**Comment by mynameiscfed** [comment] 2015-08-04 19:05
Hi - I am experiencing similiar issues of performance using Paramiko and PySFTP libraries for SFTP downloads of files in the 30-40MB range. Using the package 6.6p1-2ubuntu2 for SFTP client in Ubuntu 14.04 is giving me about 4x better download speed. 

I have tried to actively debug this issue and tune some parameters but I cannot figure it out. Curious if anyone has solved this issue or knows of some resources I may be able to use to debug this performance problem.

**Comment by manuelep** [comment] 2015-12-10 07:58
Is this thread related to [this](https://github.com/paramiko/paramiko/issues/175) other one marked as closed?
https://github.com/paramiko/paramiko/issues/175

**Comment by dioni21** [comment] 2015-12-10 14:02
There are (were) two different problems.  #175 solved a transfer speed problem, but I still have speed problems during key exchange.

**Comment by mukpat** [comment] 2016-12-29 12:03
We are facing similar problem. 500 MB file SFTP is taking 90+ minutes. Tried changing window_size to 2147483647 but it did not help. Is there any other parameter which needs to be changed?

8 MB file is taking 50 seconds 
8 KB file is taking 0.3 seconds

**Comment by jkji** [comment] 2017-02-09 21:28
@mukpat, on large files sending data in chunks may help, see #892

**Comment by DrNeutron** [comment] 2017-08-05 22:27
Hi @bitprophet 

We use Paramiko to move large CSV files between machines over long distance WAN connections (could be from a 1Mbps to 1Gbps link depending on location).  We've noticed the long transfer times noted here in #60, in our use case the issue was **when the transport was using compression**.  I know this might not apply to all the folks here with #60 issues but if you have compression read on.

Our test case is a 1.3Gb CSV file, to be moved between two machines connected by a 100Mbps lan segment.  We're running RHEL 7.3, paramiko-1.15.2 and Python 3.4.1  Sending machine is using Paramiko and receiving end is running RHEL sshd.

After getting poor reports from our production instances using Paramiko with compression we did some tests looking at multiple ways to move the file between the same servers, see results below

Transfer type | Avg time secs (3 runs) | Effective data rate
-- | -- | --
regular scp | 116 | 93 Mbps
scp with compression | 54 | 201 Mbps
gzip, scp, gunzip combo | 69 | 158 Mbps
Paramiko no compression | 117 | 93 Mbps
Paramiko with compression | 278 | 39 Mbps

This showed that Paramiko with compression was by far the slowest option, so we went digging...

The root cause of the issue in the choice of compression level in paramiko/paramiko/compress.py 
```
import zlib

class ZlibCompressor (object):
    def __init__(self):
        self.z = zlib.compressobj(9)
```
Its hard coded to 9 which is Zlib's max compression (its default is the same as gzip = 6)

To prove this out, we did the same test setting the zlib.compressobj level to 0 through 9, shown below.  We used sshd set to DEBUG level logging on the far end to record exactly how many bytes passed over the WAN/LAN.

lib Compression level | Time to send (secs) | Data over WAN MBytes | Compression %
-- | -- | -- | --
0 | 117 | 1,301 | 0%
1 | 33 | 317 | 76%
2 | 35 | 291 | 78%
3 | 37 | 269 | 79%
4 | 41 | 266 | 80%
5 | 53 | 245 | 81%
6 | 64 | 232 | 82%
7 | 74 | 227 | 83%
8 | 159 | 221 | 83%
9 | 278 | 219 | 83%

![csv transfer times vs compression](https://user-images.githubusercontent.com/30759787/28999157-e1c8d690-79f9-11e7-9698-9459a5a90b49.png)

Clearly this data is only valid for our test case of a very big CSV file, but in general we find that compression set to 9 is a bad trade off in CPU and time vs the actual gain on compression.  From our data setting the level to 8 and 9 is a terrible choice while the levels 1-4 give you a pretty good bang for the buck, a lot of this will depend just how constrained each end users WAN or LAN connection really is.

The simple fix for many people will be to alter the call to zlib.compressobj() and let zlib default to 6 or a more elegant solution would be to allow the API to pass the users requested level of compression.  We will be happy to submit a PR for this change.

**Comment by DrNeutron** [comment] 2017-08-10 19:23
Just one more note to say that the compression slowness I commented on above may also explain why a lot of people have uni-directional slowness.

The compression level is chosen by the sending end, so for example if we are doing Paramiko -> sshd put of a file with compression, we would see slow times, high CPU.  But getting exactly the same file from sshd -> Paramiko will be good performance as its the end running sshd thats doing the compression.

It could also explain the issue noted above by @Dreamsorcerer where txt files are quick and .png's are slow.  This is due to the fact the trying to re-compress an already compressed file, especially at level 9 will take much longer than squishing a txt file.

**Comment by bitprophet** [comment] 2017-08-10 19:54
Gonna be real ecstatic if that change fixes it in some/many/most cases. (FTR the hardcoded level 9 compression looks to be an arbitrary choice from literally the start of the project, 12 years ago. 😮) Thanks for doing the detailed digging, @DrNeutron!

**Closed** 2017-09-06 00:06 UTC

**Comment by bitprophet** [comment] 2017-09-06 00:13
Quick note about this: while testing #1037, it took me an embarrassingly long time to notice that no compression occurs by default - even though debug logs imply negotiation is occurring, Paramiko disables compression (by negotiating with just an option list of `["none"]`) unless you explicitly say `Client.connect(compress=True)` (or manually call `Transport.use_compression(True)`, if not using `Client`.)

So while I'm still hoping #1037 fixes the issue for folks egressing files and explicitly using compression, I wonder if that actually covers all the various "SFTP is slow" reports we've gotten over time - presumably the average user isn't remembering (or wanting) to enable compression.

**Comment by jkpubsrc** [comment] 2019-02-12 21:40
I came across this here after I did a speed test in my implementation and was very surprised: Via loopback I only got just about 1.1 MByte/s of data transfer rate. This is a show stopper. As this obviously has not yet been resolved till now I need to reject the use of paramiko :-(

**Comment by ramei** [comment] 2019-03-26 22:25
does any has a solution for slow paramiko performance. i am transferring 15 GB of data which takes around 45 minutes. normal scp takes only around 7 minutes. 
any welcome would be great. thanks

**Comment by svanscho** [comment] 2019-06-11 07:08
Same here - is this a recent regression?

**Comment by BedivereZero** [comment] 2020-02-24 04:45
same problem
paramiko only 4MB/s
but command `scp`, `sftp` nearly 100MB/s

I try to change window_size, max_package_size and compress, no change.

**Comment by sakisv** [comment] 2021-01-18 11:53
We had the same problem and we [solved it] with these two changes:

1. We used the [`set_pipelined`] to reduce the time waiting to hear back from the server
2. We changed our data to  [`memoryview`] objects to take care of this bottleneck here: https://github.com/paramiko/paramiko/blob/5cf145ffd3d7cd4d96a511376267a7f27cce5eed/paramiko/file.py#L523

Locally, for a 100MB file this reduced the time to transfer from 254s to 3.4s.

[`set_pipelined`]: https://paramiko-docs.readthedocs.io/en/latest/api/sftp.html#paramiko.sftp_file.SFTPFile.set_pipelined
[`memoryview`]: https://docs.python.org/3/c-api/memoryview.html
[solved it]: https://github.com/alphagov/notifications-ftp/pull/309

**Comment by jowparks** [comment] 2022-04-20 21:45
FWIW to any future reader, it looks like this was fixed here:
https://github.com/paramiko/paramiko/issues/892

**Comment by Dreamsorcerer** [comment] 2022-04-21 16:30
Also, more recently, I've found this issue too: https://github.com/pyinvoke/invoke/issues/819
Which also causes severe speed drops, if you end up hitting it in your code.
