### ISSUE TITLE
Session not active, and Channel Closed Exceptions

### ISSUE THREAD

**Issue by GoelJatin** [paramiko/paramiko#1011] opened 2017-07-05 10:46 UTC
I'm working on a project where I'm using paramiko to run commands remotely on a Linux / UNIX client.

For Linux (**TTL < 64**), everything is working fine.

But, for UNIX (**TTL < 255**), when we connect to the client, and run the first command, it puts the session as inactive.
**Transport.active** property is set to **False**

When I run the second command, it is raising the exception: (**SSHException: SSH session not active**)

If I just connect to the client, and don't run any command, and try to open the SFTP channel, it raises the exception: (**SSHException: Channel closed.**)

Issues #928 , and #513 , are already open for this, but I did not see any update on them, so thought of putting them together, and providing as much info, as I could.

Following are the scenarios in which a specific exception is being raised.

* **SSHException: SSH session not active**

1. Here in the attached snapshot, when I executed a command first time, it ran successfully, but failed for the consecutive runs.
![image](https://user-images.githubusercontent.com/14715892/27860895-2c31e3f0-619c-11e7-9dc2-9c9b9d75a416.png)

2. If I try to open SFTP channel after this, it fails with the same exception.
![image](https://user-images.githubusercontent.com/14715892/27860771-a489740e-619b-11e7-940d-99c12569e35a.png)

* **SSHException: Channel closed.**
1. Now if I try to open the SFTP channel without even running a single command prior to it, it raises the **Channel closed** exception.
![image](https://user-images.githubusercontent.com/14715892/27860993-8b0962fe-619c-11e7-96bf-1d11feeec56e.png)

I hope this info is enough to get started with the issue, and I'll also try to find more about it, and the possible solutions.

**Thanks,
-Jatin**

**Comment by GoelJatin** [comment] 2017-07-14 04:59
Team,
Haven't heard anything on this.
Is anyone checking this?

**Comment by ploxiln** [comment] 2017-07-14 17:01
No one has enough information or motivation to debug your problem, you're on your own there.

When you refer to `TTL`, you mean the time-to-live in the IPv4 (or IPv6 packet) header? Why do you think that is significant for this problem?

What UNIX are you referring to - macOS, FreeBSD, OpenBSD, Solaris? What version?

When you say `I'm using paramiko to run commands remotely on a Linux / UNIX client` do you mean that you're running paramiko on a "Linux / UNIX" client or that it is  connecting to a "Linux / UNIX" server to run the commands?

It seems like, in the not-working case, the SSH server which you are connecting to is closing down the ssh connection after the first channel is closed. Every time you do `exec_command()` it uses a new "channel" within the same SSH connection. You could alternatively do something like `invoke_shell()` to keep using a single channel for multiple commands (but then its up to you to use the remote shell interactively and detect when one command has finished).

**Comment by craneworks** [comment] 2018-09-27 10:21
I use `paramiko` and `exec_command` for a bunch of unittests that executes commands through ssh on a remote location.
Both, client and server, are running on Debian Stretch with python3.6.6. Note that the server is a self written SSH server using `Twisted` Framework. So the error might also be in the server itself or on my site using `paramiko` the wrong way.

The error rate here is 90-98% which means that it is not deterministic for me when `paramiko.ssh_exception.SSHException: Channel closed.` is being raised. This happens also to the first `exec_command` I try to fire using this connection.

The connection itself is not the problem. For example I can use `invoke_shell()` and do everything on my own.

I'm happy to give you more information if needed. :)

My Connection class
```python
        self.connection = SSHClient()
        self.connection.set_missing_host_key_policy(AutoAddPolicy())
[...]
    def _connect(self):
        try:
            self.connection.connect(self.ip, self.port, self.username, self.password)
        except AuthenticationException as err:
            raise err
        except NoValidConnectionsError as err:
            raise err
[...]
    def exec(self, cmd):
        try:
            stdin_, stdout_, stderr_ = self.connection.exec_command(cmd, timeout=5)
        except TimeoutError as err:
            raise err
        else:
            stdout_.channel.recv_exit_status()
```

The result
```python
F
functional_tests/commands_test.py:38 (TestCommands.test_execute_00001_nohup)
self = <integration_tests.functional_tests.commands_test.TestCommands testMethod=test_execute_00001_nohup>
command = 'nohup'

    @idata(_read_commands_from_source())
    def test_execute(self, command):
        test_start_time = int(time.time())
>       self.connection.exec(command)

test/integration_tests/functional_tests/commands_test.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/integration_tests/helpers/connection.py:31: in exec
    stdin_, stdout_, stderr_ = self.connection.exec_command(cmd, timeout=5)
/usr/local/lib/python3.6/dist-packages/paramiko/client.py:499: in exec_command
    chan.exec_command(command)
/usr/local/lib/python3.6/dist-packages/paramiko/channel.py:72: in _check
    return func(self, *args, **kwds)
/usr/local/lib/python3.6/dist-packages/paramiko/channel.py:257: in exec_command
    self._wait_for_event()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <paramiko.Channel 0 (closed) -> <paramiko.Transport at 0x197aa58 (cipher aes128-ctr, 128 bits) (active; 0 open channel(s))>>

    def _wait_for_event(self):
        self.event.wait()
        assert self.event.is_set()
        if self.event_ready:
            return
        e = self.transport.get_exception()
        if e is None:
            e = SSHException("Channel closed.")
>       raise e
E       paramiko.ssh_exception.SSHException: Channel closed.

/usr/local/lib/python3.6/dist-packages/paramiko/channel.py:1208: SSHException
```

**Comment by jadhavmanoj** [comment] 2020-06-03 07:01
I am not able to run `screen` command . I want to create screen and run multiple command. 

When I send command `screen ls` it says - ```Must be connected to a terminal.```

**Comment by chrisinmtown** [comment] 2023-03-27 14:53
> I am not able to run `screen` command . I want to create screen and run multiple command.
> 
> When I send command `screen ls` it says - `Must be connected to a terminal.`

Did you try setting parameter `get_pty=True` in the `exec_command` call?

**Comment by chrisinmtown** [comment] 2023-03-27 15:43
Here's a brutal hack that lets me run two commands in quick succession on a Cisco device. After opening a Paramiko  connection in `client` I added this line of code:
```
        chan = client.invoke_shell()
```
Then my script calls `exec_command` twice, gets back the output and finally closes the channel and the client. 

I would like to know if this extra line of code is telling the *server* to stick around, or changing the *client* library behavior, or both. Works for now, but sure feels dirty!

**Comment by chrisinmtown** [comment] 2023-03-27 17:22
Thanks for the pointer to netmiko.

I still don't think Paramiko's session-not-active issue is specific to Cisco devices. Based on SO posts and the other people who posted to this issue, it seems I'm not alone. I still think there might be something a big odd going on inside Paramiko that I managed to work around by creating an SSH session, even tho I don't actually use it.

**Comment by chrisinmtown** [comment] 2023-03-31 21:05
Here's a SSCCE that demonstrates the hack I mentioned above, which is not required when connecting to a Debian host - there paramiko happily runs several commands in succession without any problem. But when connecting to a local Cisco host, paramiko runs the first command then raises `EOFError` on the second. The hack, calling the `invoke_shell()` method, lets this script run multiple commands on the Cisco host.  HTH
```
"""
Demontrates a brutal hack to run multiple
commands on a Cisco device using paramiko.
"""
import argparse
from getpass import getpass
import paramiko


def ssh_run_cmds(host: str, port: int, user: str, pswd: str,
                 shell: bool, cmds: list) -> list:
    """
    Use paramiko to establish an ssh connection with
    the specified credentials and run the commands.

    :param host: hostname/IP
    :param user: user name
    :param pswd: password
    :param shell: if True call invoke_shell
    :param cmds: list of commands to execute
    """
    print(f'Connect to host {host} port {port} as user {user}')
    client = None
    chan = None
    try:
        client = paramiko.client.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(hostname=host, port=port,
                       username=user, password=pswd,
                       look_for_keys=False,
                       # parameter required for Cisco device
                       allow_agent=False)
        # invoke shell to allow second (third, ..) command
        if shell:
            chan = client.invoke_shell()
        for c in cmds:
            print(f'Run command {c}')
            _in, _out, _err = client.exec_command(c, timeout=3)
            stdout = _out.read().decode()
            print(f'host {host} command {c} yields:')
            print(stdout)
            print('---')
    finally:
        if chan is not None:
            chan.close()
        if client is not None:
            client.close()


def main(args=None) -> None:
    parser = argparse.ArgumentParser(
        description='SSCCE for paramiko multiple commands')
    parser.add_argument(
        '-r', '--remote', required=True, help='remote host name')
    parser.add_argument(
        '-o', '--port', help='remote host port', default=22)
    parser.add_argument(
        '-u', '--user', required=True, help='remote host user name')
    # Allow user to enter password securely on the command line
    parser.add_argument(
        '-p', '--password',
        help='Password for the credential (default: prompt if not specified)')
    parser.add_argument(
        '-s', '--shell', action='store_true', help='invoke shell')
    parser.add_argument('rest', nargs=argparse.REMAINDER)
    args = parser.parse_args(args)
    password = args.password if args.password else getpass('password: ')
    ssh_run_cmds(args.remote, args.port, args.user, password,
                 args.shell, args.rest)


if __name__ == '__main__':
    main()
```

**Comment by chrisinmtown** [comment] 2023-07-14 15:30
I worked up a new SSCCE to demonstrate the different behavior of a classic Linux SSH server verus a Cisco IOS SSH server. On the former, the code works - it can open multiple channels using a connected `Transport` object, run a command in each. On the latter, the code fails - it can only open a single channel using the `Transport` object; the session is dead after processing the first command. I noticed this logger output appears only when running against a Cisco IOS SSH server:
```
DEBUG:paramiko.transport:EOF in transport thread
```
 I believe that when reading the first command output from the router, Paramiko decides it has seen EOF, and sets the `Transport` object's `active` attribute to False.  I checked where that message shown above comes from, added a `raise` on line 2194 of `transport.py` (yes sorry I modified your code) and then was able to see this trace:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/me/.virtualenvs/py39/lib/python3.9/site-packages/paramiko/transport.py", line 2109, in run
    ptype, m = self.packetizer.read_message()
  File "/Users/me/.virtualenvs/py39/lib/python3.9/site-packages/paramiko/packet.py", line 453, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/Users/me/.virtualenvs/py39/lib/python3.9/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()
```
I would like to ask you all the question, are you sure Paramiko is interpreting the return value(s) from the Cisco router appropriately? Anyhow, you can run this code like this:
```
python3 sscce.py -r your-host-name -o your-port-number -u your-user-name -p your-password "ls -a"
```
Here's the code:
```
'''
SSCCE to demonstrate use of a Paramiko Transport and Channel.
'''
import argparse
from getpass import getpass
import logging
import paramiko
import socket
import time

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


def ssh_run_cmd(
        host: str,
        port: int,
        user: str,
        pw: str,
        command: str) -> None:
    """
    Connect to the router, authenticate by password, get a
    channel, then run the command and get output twice.
    """
    # Create a socket and connect it to port 22 on the remote host
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # the argument must be a tuple
    sock.connect((host, port))
    # Wrap the socket in a paramiko Transport object
    ts = paramiko.Transport(sock)
    # Tell Paramiko that the Transport is going to be used as a client
    ts.start_client(timeout=10)
    # Authenticate
    ts.auth_password(user, pw)
    for i in range(2):
        # Open a channel
        # The second pass works on a classic Linux SSH server
        # but fails on a Cisco router with this exception:
        # paramiko.ssh_exception.SSHException: SSH session not active
        chan = ts.open_channel(kind='session', timeout=10)
        # Execute the command
        logger.debug('send command %s', command)
        chan.exec_command(command)
        # Read the command result
        timeout = 10
        while timeout and not chan.recv_ready():
            time.sleep(1)
            timeout -= 1
        data = chan.recv(16384)
        logger.debug('out %s', data.decode())
        chan.close()
    # for

    ts.close()
    sock.close()


def main(args=None) -> None:
    parser = argparse.ArgumentParser(
        description='SSCCE for Paramiko Transport and Channel')
    parser.add_argument(
        '-r', '--remote', required=True, help='remote host name')
    parser.add_argument(
        '-o', '--port', help='remote host port', default=22)
    parser.add_argument(
        '-u', '--user', required=True, help='remote host user name')
    # Allow user to enter password securely on the command line
    parser.add_argument(
        '-p', '--password', help='Password (will prompt)')
    parser.add_argument(
        'rest', nargs=argparse.REMAINDER, help='IOS command to run')
    args = parser.parse_args(args)
    if not args.rest:
        raise Exception('Missing command(s)')
    if len(args.rest) > 1:
        raise Exception('Too many commands')
    pw = args.password if args.password else getpass('Password: ')
    ssh_run_cmd(host=args.remote,
                port=int(args.port),
                user=args.user,
                pw=pw,
                command=args.rest[0])


if __name__ == '__main__':
    main()
```

**Comment by jun66j5** [comment] 2023-07-14 16:10
@chrisinmtown Please provide log after adding  `paramiko.util.log_to_file('paramiko.log')` to your script. Also,  several switch devices disconnects the connection after performing exec_command request. This behavior is the switch device's issue depended on the SSH implementation, not a paramiko issue.

**Comment by chrisinmtown** [comment] 2023-07-14 16:47
For what it's worth, this Cisco SSH server seems to support `exec` channel just fine. I tested by running  at the command line `ssh myuser@myrouter show version`, it prompted me for my password then happily showed the router's version.

I'm happy to provide the log from running the code example pasted above. I don't see much helpful information in it tho.
```
DEB [20230714-12:45:01.232] thr=1   paramiko.transport: starting thread (client mode): 0x971d460
DEB [20230714-12:45:01.232] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_3.1.0
DEB [20230714-12:45:01.410] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-Cisco-2.0
INF [20230714-12:45:01.410] thr=1   paramiko.transport: Connected (version 2.0, client Cisco-2.0)
DEB [20230714-12:45:01.463] thr=1   paramiko.transport: === Key exchange possibilities ===
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: kex algos: ecdh-sha2-nistp521, ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-ed25519
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, aes128-cbc, aes192-cbc, aes256-cbc
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, aes128-cbc, aes192-cbc, aes256-cbc
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: client mac: hmac-sha2-512, hmac-sha2-256, hmac-sha1
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: server mac: hmac-sha2-512, hmac-sha2-256, hmac-sha1
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: client compress: none
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: server compress: none
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: client lang: <none>
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: server lang: <none>
DEB [20230714-12:45:01.464] thr=1   paramiko.transport: kex follows: False
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: === Key exchange agreements ===
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: Kex: ecdh-sha2-nistp256
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: HostKey: ssh-ed25519
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: Cipher: aes128-ctr
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: MAC: hmac-sha2-256
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: Compression: none
DEB [20230714-12:45:01.465] thr=1   paramiko.transport: === End of kex handshake ===
DEB [20230714-12:45:01.724] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20230714-12:45:01.778] thr=1   paramiko.transport: Switch to new keys ...
DEB [20230714-12:45:02.035] thr=1   paramiko.transport: userauth is OK
INF [20230714-12:45:02.402] thr=1   paramiko.transport: Auth banner: b'\nYou are now in Privilege Class\n'
INF [20230714-12:45:02.461] thr=1   paramiko.transport: Authentication (password) successful!
DEB [20230714-12:45:02.462] thr=2   paramiko.transport: [chan 0] Max packet in: 32768 bytes
DEB [20230714-12:45:02.517] thr=1   paramiko.transport: [chan 0] Max packet out: 32768 bytes
DEB [20230714-12:45:02.517] thr=1   paramiko.transport: Secsh channel 0 opened.
DEB [20230714-12:45:02.581] thr=1   paramiko.transport: [chan 0] Sesch channel 0 request ok
DEB [20230714-12:45:02.899] thr=1   paramiko.transport: [chan 0] EOF received (0)
DEB [20230714-12:45:02.900] thr=1   paramiko.transport: [chan 0] EOF sent (0)
DEB [20230714-12:45:02.900] thr=1   paramiko.transport: EOF in transport thread
```

**Comment by chrisinmtown** [comment] 2023-07-14 16:51
> .. Also, several switch devices disconnects the connection after performing exec_command request.

I believe that the SSCCE I posted on Mar 31 demonstrates that this particular device does not disconnect after the first `exec_command`. That example code is just a little weird - calls both `invoke_shell()` and `exec_command` - but achieves the desired effect of allowing multiple commands without reopening the connection.

**Comment by jun66j5** [comment] 2023-07-14 17:36
> For what it's worth, this Cisco SSH server seems to support `exec` channel just fine. I tested by running at the command line `ssh myuser@myrouter show version`, it prompted me for my password then happily showed the router's version.

`ssh user@host command` cannot send multiple command to remote server on single connection. It can check `exec` request is supported but cannot check whether multiple `exec` requests are supported on single connection.

**Comment by jun66j5** [comment] 2023-07-14 23:31
> But this might also just be seriously muddle-headed thinking. Please let me know what I should try.

No way to send multiple `exec` requests on single connection if remote server is a CISCO device. It is caused by that the CISCO device closes the connection on performing `exec` request.

I'm unsure why you want to send `exec` requests on single connection. Instead, try to connect on each `exec` request, or use `invoke_shell` (see https://github.com/paramiko/paramiko/issues/2238#issuecomment-1529402143 to handle termination of commands on shell).

**Comment by bskinn** [comment] 2023-07-20 02:48
As this is about a quirk of Cisco devices and a solution to the OP's problem appears to have been identified, I'm going to close this ticket for now.

Please feel free to keep discussing!

And, if anyone has a similar problem but the above doesn't help your situation, please open a new issue.

**Closed by bskinn** 2023-07-20 02:48 UTC
Labels: Nonstandard platforms, Support
