### ISSUE TITLE
paramiko 1.16 error in _winapi.py

### ISSUE THREAD

**Issue by hobbsd** [paramiko/paramiko#613] opened 2015-11-06 04:11 UTC
Here's the end of the traceback:

    ...\paramiko\_winapi.py", line 162, in write
    ctypes.windll.kernel32.RtlMoveMemory(dest, msg, length)
    ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Using Python 2.7 on Windows 7.

**Comment by bitprophet** [comment] 2015-11-09 01:00
Paging Dr @jaraco, Dr @jaraco to aisle 613. Hoping I just made some stupid merge error in that module or something?

**Comment by jaraco** [comment] 2015-11-09 15:29
The error message strikes me as something I've seen before, but I don't recall exactly what the issue is. That call in particular is tested in [test_mmap](https://bitbucket.org/jaraco/jaraco.windows/src/ea931d3afa0a8bf690803a2a1bf8936087bf8f30/tests/test_mmap.py?at=default&fileviewer=file-view-default) and passes on Python 2.7 on Windows 10. I'll keep looking.

**Comment by jaraco** [comment] 2015-11-09 16:36
I just tested with Paramiko 1.16.0 and I was able to establish a connection using Python 2.7.10 64-bit and Pageant 0.65 64-bit on Windows 10 64-bit.

@hobbsd Can you tell me more about your environment - what versions (and bit size) of Windows, Putty, and Python are you using?

**Comment by hobbsd** [comment] 2015-11-09 19:34
I'm using Python 2.7.9 32-bit on Windows 7 64-bit with Putty 0.65.

**Comment by jaraco** [comment] 2015-11-10 22:05
The error seems to be [unique to 32-bit Python](https://bitbucket.org/jaraco/jaraco.windows/issues/5/valueerror-in-mmap-on-32-bit-python). I'll devise a fix. In the meantime, I suspect you'll have success with 64-bit Python.

**Comment by dkmstr** [comment] 2015-11-12 17:19
Changing the MemoryMap class, the read & write methods as you refer in the reference, it works fine!!
I had the same issue on a machine, an after changing
length = ctypes.wintypes.SIZE(n)
by
length = ctypes.c_size_t(n)
in both read & write method, now paramiko works perfectly :-)

Thanks for the references and your good work!!

**Comment by NormanDenayer** [comment] 2015-11-18 09:23
I had the same issue with Python 3.4 32bits on Windows7.
I applied the same fix on "length = ctypes.wintypes.SIZE(n)" in read and right method.
It works great now. Thank you @dkmstr

**Comment by StdioA** [comment] 2015-12-09 12:43
Had the same issue with Python 2.7 32bits on Windows 10 Build 10576.
Maybe the api changes after the Windows upgrades from 10240 to 10576, so that the function RtlMoveMemory failed.
Here's the traceback:
> File "C:\Python27\lib\site-packages\paramiko\_winapi.py", line 162, in write
>     ctypes.windll.kernel32.RtlMoveMemory(dest, msg, length)
> ValueError: Procedure probably called with too many arguments (4 bytes in excess)

**Comment by bitprophet** [comment] 2015-12-11 00:35
Not sure why I didn't close this to merge w/ the PR, doing that now. Please follow #619. It's part of the next bugfix milestone!

**Closed by bitprophet** 2015-12-11 00:35 UTC
Labels: Bug, Nonstandard platforms

**Comment by jameshume** [comment] 2015-12-15 10:14
Phew... that fixed it for me running on windows XP. A big thank you to you!!

**Comment by DrayChou** [comment] 2016-02-16 03:13
I'm using Python 2.7.11 32-bit on Windows 7 64-bit.
and I applied the same fix on "length = ctypes.wintypes.SIZE(n)" in read and right method.
It works great now. Thank you @dkmstr

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 15, in ssh2
    ssh.connect(ip,22,username,passwd,timeout=5)
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 517, in _auth
    self._agent = Agent()
  File "C:\Python27\lib\site-packages\paramiko\agent.py", line 363, in __init__
    self._connect(conn)
  File "C:\Python27\lib\site-packages\paramiko\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "C:\Python27\lib\site-packages\paramiko\agent.py", line 83, in _send_message
    self._conn.send(struct.pack('>I', len(msg)) + msg)
  File "C:\Python27\lib\site-packages\paramiko\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "C:\Python27\lib\site-packages\paramiko\win_pageant.py", line 92, in _query_pageant
    pymap.write(msg)
  File "C:\Python27\lib\site-packages\paramiko\_winapi.py", line 162, in write
    ctypes.windll.kernel32.RtlMoveMemory(dest, msg, length)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)

**Comment by zapu** [comment] 2016-03-04 00:32
Same issue, the fix mentioned helped.

I'm using `fabric` on Windows 7, with Python 2.7. My packages are installed with pip, apart from `pycrypto`, which I got from http://www.voidspace.org.uk/python/modules.shtml#pycrypto Is the version 1.16.0 (with the bug described in this issue) the last version for this Python or am I missing something? Thanks.

**Comment by dmikov** [comment] 2016-03-15 00:38
Any eta on fix? I cannot go and change ctype ine on my machine. Our clients download pip at there premises so I cannot fix it on hundreds of servers.

**Comment by Dagur** [comment] 2016-04-06 11:06
@zapu I have the same setup. Reverting back to paramiko 1.15.4 fixed the error for me

**Comment by ArmanFazylov** [comment] 2016-04-07 06:06
@Dagur tnx for help! Fixed for me too

**Comment by bitprophet** [comment] 2016-04-24 20:30
#619 is merged, expect release of 1.16.1 soon.
