### ISSUE TITLE
ProxyCommandFailure Broken Pipe

### ISSUE THREAD

**Issue by tyrostone** [paramiko/paramiko#655] opened 2016-01-07 19:06 UTC
I am getting a ProxyCommandFailure exception when using paramiko with ProxyCommand to SSH through a NAT. The code generating this exception executes as a method within a class. I have tested this with both paramiko 1.15.1 and 1.15.2. The stack trace from paramiko's log is the following:

DEB [20160107-13:20:56.872] thr=1   paramiko.transport: starting thread (client mode): 0xb280fd0L
ERR [20160107-13:20:56.872] thr=1   paramiko.transport: Exception: ('ssh -A 52.27.182.234 nc 10.161.99.122 22', 'Broken pipe')
ERR [20160107-13:20:56.874] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20160107-13:20:56.874] thr=1   paramiko.transport:   File "/Users/lstone/.virtualenvs/aws/lib/python2.7/site-packages/paramiko/transport.py", line 1581, in run
ERR [20160107-13:20:56.874] thr=1   paramiko.transport:     self.packetizer.write_all(b(self.local_version + '\r\n'))
ERR [20160107-13:20:56.874] thr=1   paramiko.transport:   File "/Users/lstone/.virtualenvs/aws/lib/python2.7/site-packages/paramiko/packet.py", line 238, in write_all
ERR [20160107-13:20:56.874] thr=1   paramiko.transport:     n = self.__socket.send(out)
ERR [20160107-13:20:56.874] thr=1   paramiko.transport:   File "/Users/lstone/.virtualenvs/aws/lib/python2.7/site-packages/paramiko/proxy.py", line 70, in send
ERR [20160107-13:20:56.874] thr=1   paramiko.transport:     raise ProxyCommandFailure(' '.join(self.cmd), e.strerror)
ERR [20160107-13:20:56.875] thr=1   paramiko.transport: ProxyCommandFailure: ('ssh -A 52.27.182.234 nc 10.161.99.122 22', 'Broken pipe')

Using pdb, I've seen the exception be thrown when running the line ```ssh.connect(**cfg)```.

Here is the code:
```
def _send_config_files(self):
        for f in InstanceCreator.CONFIG_FILES:
            file_sent = False
            while not file_sent:
                self.scp_file(f)

def scp_file(self, filename):
        ssh_up = False
        while not ssh_up:
            time.sleep(30)
            try:
                ssh = SSHClient()
                ssh.load_system_host_keys()
                ssh.set_missing_host_key_policy(AutoAddPolicy())

                cfg = {}
                cfg['hostname'] = self.instance.private_ip_address
                cfg['username'] = InstanceCreator.USERNAME
                cfg['sock'] = ProxyCommand("ssh -A {} nc {} 22".format(
                    self.gateway.ip_address, self.instance.private_ip_address))

                ssh.connect(**cfg)
                ssh_up = True
            except SSHException:
                pass

        scp = SCPClient(ssh.get_transport())

        try:
            scp.put("{}/config/{}".format(
                os.path.abspath("."), filename), "/tmp/{}".format(filename))
            return True
        except Exception:
            return False
```

I am able to manually SSH to both the NAT and the host in question without problem. Thoughts? 

Thanks!

**Comment by tyrostone** [comment] 2016-01-18 17:07
Any update on this?

**Comment by kaaveland** [comment] 2016-01-19 07:01
This is probably a dupe of https://github.com/paramiko/paramiko/issues/495 -- your traceback looks slightly different, which could probably help narrow it down.

**Closed** 2016-01-19 22:50 UTC
