### ISSUE TITLE
width_pixels and height_pixels default value may not good for program

### ISSUE THREAD

**Issue by qhsong** [paramiko/paramiko#870] opened 2016-12-24 15:44 UTC
When I use following code to run a command:
```python
client.exec_command("ls -a")
```
We can not set `width_pixels` and `height_pixels`, some server will refuse to run this command because `width_pixels` and `height_pixels` are zero.

So I think maybe we can add them into `client.exec_command()`  parameter list and give them a default non-zero value. Or change `chan.get_pty()` and `client.invoke_shell()` function default value to non-zero.

I'm not sure is it good and why that default value is zero.

**Comment by bitprophet** [comment] 2017-01-05 19:17
There's no good way to arrive at a clean nonzero default value for those, as far as I know, given that Paramiko code may be running without its own controlling PTY, etc etc.

Typically, shortcomings in Client just mean you should drop down to Channel directly, which is what eg Fabric does, see here where it sets the other (non pixel specific) pty size params (and in which spot one could presumably also set the pixel versions of same): https://github.com/fabric/fabric/blob/5d2e61cc78fe7a86f8ef4c6a167d7207ac1c4839/fabric/operations.py#L767-L785

Going to close this for now as "probably not worth implementing right now" (esp since we hope to do more general work around unifying Client with higher level tools I manage like Fabric) but please feel free to continue the discussion. Thanks!

**Closed by bitprophet** 2017-01-05 19:17 UTC

**Comment by radssh** [comment] 2017-01-05 20:23
In the SSH protocol RFC [4252](https://www.ietf.org/rfc/rfc4254.txt), the pty-req specification notes that zero dimension parameters MUST be ignored (by the server). That would seem to make zero as the only sensible client default values.

The issue may be related to the TERM field or the encoded terminal modes instead, if it is directly caused by the result of the get_pty() call.

**Comment by qhsong** [comment] 2017-01-06 05:49
@bitprophet  Thanks for your reply, I think Fabric code is best way to use. I also use Paramiko like that.It is a good reason to do like that.

@radssh I have use `get_pty` instead of `exec_command` to avoid this problem. 

Thanks for answering this.
