### ISSUE TITLE
paramiko causing Warnings due to Blowfish deprecation in cryptography 37.0.0

### ISSUE THREAD

**Issue by repl-mike-roest** [paramiko/paramiko#2038] opened 2022-04-26 20:38 UTC
cryptography released a new version 37.0.0 in which they deprecated blowfish: https://github.com/pyca/cryptography/pull/6922

We're now getting this warning output:
```
tests/test_dag_contents.py:7: in <module>
    import rail
.venv/lib/python3.9/site-packages/rail/__init__.py:33: in <module>
    from .operators.network.sftp_any_file_sensor import SFTPAnyFileSensor
.venv/lib/python3.9/site-packages/rail/operators/network/sftp_any_file_sensor.py:5: in <module>
    from airflow.providers.sftp.hooks.sftp import SFTPHook
.venv/lib/python3.9/site-packages/airflow/providers/sftp/hooks/sftp.py:24: in <module>
    import pysftp
.venv/lib/python3.9/site-packages/pysftp/__init__.py:12: in <module>
    import paramiko
.venv/lib/python3.9/site-packages/paramiko/__init__.py:22: in <module>
    from paramiko.transport import SecurityOptions, Transport
.venv/lib/python3.9/site-packages/paramiko/transport.py:132: in <module>
    class Transport(threading.Thread, ClosingContextManager):
.venv/lib/python3.9/site-packages/paramiko/transport.py:236: in Transport
    "class": algorithms.Blowfish,
.venv/lib/python3.9/site-packages/cryptography/utils.py:123: in __getattr__
    warnings.warn(obj.message, obj.warning_class, stacklevel=2)
E   cryptography.utils.CryptographyDeprecationWarning: Blowfish has been deprecated
```

During part of our build as paramiko appears to be referencing blowfish in it's transport options.

I'd be more then willing to submit a PR to remove blowfish from the paramiko transport ciphers to clear this deprecation warning.

**Comment by SophisticaSean** [comment] 2022-04-27 19:52
Currently experiencing this issue, would love to see #2039 merged and a release cut

**Comment by earlruby** [comment] 2022-04-27 21:38
Also experiencing this issue, would love to see https://github.com/paramiko/paramiko/pull/2039 merged and a release cut.

**Comment by earlruby** [comment] 2022-04-27 21:40
If you want to see https://github.com/paramiko/paramiko/pull/2039 merged, go to the MR and click "thumbs up" on the MR.

**Comment by tanus10** [comment] 2022-04-27 22:13
docker-compose installed by pip3 is affected by this too.

**Comment by che-belew** [comment] 2022-04-27 23:37
Ran into this issue while using `fabric`.

**Comment by che-belew** [comment] 2022-04-28 23:20
> Ran into this issue while using `fabric`.

My temp workaround for my automation is pining `cryptography` after `paramiko`/ `fabric` install.
```
pip install fabric
pip uninstall -y cryptography # uninstalls 37.0.0
pip install cryptography==36.0.2
```

**Comment by tanus10** [comment] 2022-04-29 01:40
I applied the proposed patch manually. Works without a problem. As a workaround,  downgrade and pinning sounds better.

**Comment by jun66j5** [comment] 2022-04-29 14:16
Another workaround is ignoring warnings from cryptography.

```python
import warnings
from cryptography.utils import CryptographyDeprecationWarning
with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=CryptographyDeprecationWarning)
    import paramiko
```

**Comment by bskinn** [comment] 2022-05-02 16:16
From talking to @bitprophet, given that workable pinning/pip-fu/warning-suppression strategies have been identified to deal with these warnings, there's not going to be a specific release for fixing this. However, a fix will get pulled into a near-term future release.

**Comment by neilyoung** [comment] 2022-05-09 13:23
Also ansible "infected"... :)

**Comment by batchenr** [comment] 2022-05-12 12:08
Im having this issue now after i re-build a container that uses ansible and none of the work around work for me, i get errors that i didnt have before on my playbook :  
```
TASK [Get facts] *******************************************************************************************************************
[WARNING]: Skipping plugin (/usr/local/lib/python3.7/site-packages/ansible/plugins/filter/core.py) as it seems to be invalid:
cannot import name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.7/site-packages/jinja2/filters.py)
[WARNING]: Skipping plugin (/usr/local/lib/python3.7/site-packages/ansible/plugins/filter/mathstuff.py) as it seems to be invalid:
cannot import name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.7/site-packages/jinja2/filters.py)
[DEPRECATION WARNING]: Classic provider params are deprecated; use "provider" instead. This feature will be removed in version 
2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [debug] ***********************************************************************************************************************
[WARNING]: Skipping plugin (/usr/local/lib/python3.7/site-packages/ansible/plugins/filter/core.py) as it seems to be invalid:
cannot import name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.7/site-packages/jinja2/filters.py)
[WARNING]: Skipping plugin (/usr/local/lib/python3.7/site-packages/ansible/plugins/filter/mathstuff.py) as it seems to be invalid:
cannot import name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.7/site-packages/jinja2/filters.py)
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: No filter named 'from_json'.. String: {{ facts['ansible_facts'] | to_json | from_json | json_query('ansible_net_interfaces[?starts_with(name,`ae2`)].name') | list| sort |version_sort }}"}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

is it related? i dont know what to do it all started after rebuild :(
using ansible 2.9.7
python version = 3.7.4

**Comment by batchenr** [comment] 2022-05-12 13:02
Updating that on ansible 2.9.22 now the playbook issue is ok and fixed the error of "CryptographyDeprecationWarning: Blowfish" by editing the "/usr/local/lib/python3.7/site-packages/paramiko/transport.py" file as suggested above and mounting it to container

**Comment by abhinavsingh** [comment] 2022-05-12 15:33
Our workflows have started to fail likely due to this issue.   `pytest` simply errors out.  Pinning cryptography didn't help either.  Please suggest a workable workaround.

**Comment by bitprophet** [comment] 2022-05-13 18:23
As I noted in [another recent comment](https://github.com/paramiko/paramiko/issues/2041#issuecomment-1126266035) I want to raise the point that _most of the time_, "a dependency is throwing a warning" is something users ought to be prepared to deal with themselves. If you find yourself asking upstream to make changes so you don't have to write a few lines of `warnings` module related code...maybe reconsider? 😅 

**However!!** in this case, because:

* a "choice" by Paramiko instead of the user, is what's triggering the warning
    * and further, because we haven't yet made cipherlists easily configurable - see #2054
* the warning itself is "a good point" (Blowfish is now pretty weak and discouraging its use is likely a good thing)

I think this merits an exception to that rule, so I'll merge #2039, probably to a 2.11.0 release, just because removing something in a bugfix release strikes me as a little weird.

**Comment by bitprophet** [comment] 2022-05-13 18:27
Thanks for this @repl-mike-roest !

**Closed** 2022-05-13 18:26 UTC

**Comment by cthart** [comment] 2022-05-17 12:11
Thanks for the 2.11.0 release. I just upgraded.

**Comment by Dr-Bix** [comment] 2023-10-26 16:11
I made these changes in `/usr/lib/python3/dist-packages/paramiko/transport.py`:

```
    _preferred_ciphers = (
        "aes128-ctr",
        "aes192-ctr",
        "aes256-ctr",
        "aes128-cbc",
        "aes192-cbc",
        "aes256-cbc",
#        "blowfish-cbc",
        "3des-cbc",
    )

#        "blowfish-cbc": {
#            "class": algorithms.Blowfish,
#            "mode": modes.CBC,
#            "block-size": 8,
#            "key-size": 16,
#        },


```

**Comment by Eheran1** [comment] 2024-08-19 08:30
Odd that I still get this error today with a fresh environment using Python 3.11:
`C:\Users\me\.conda\envs\my_env\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release
  "class": algorithms.Blowfish,`

Commands to reproduce:
```
conda create --name my_env python=3.11
conda activate my_env
conda install anaconda
conda install -c conda-forge scikits.odes 
pip install scipy numpy pandas matplotlib ttkthemes cython
spyder
```
While stating up Spyder (which happens to be V5.5.1), the above mentioned error appears.

**Comment by bskinn** [comment] 2024-08-19 18:34
@Eheran1 What version of paramiko shows up when you either `conda list` or `pip list` the installed packages?

It looks like there's a package getting installed from Anaconda or conda-forge that has an out-of-date version of paramiko published.

paramiko has no control over the versions of itself that are packaged into these channels, so you'd need to do some digging to find out where paramiko is coming from, and then report this warning in those channels.

**Comment by Eheran1** [comment] 2024-08-30 11:25
`conda list`
 `paramiko                  2.8.1              pyhd3eb1b0_0`
`pip list`
`paramiko                  2.8.1 `

Seems like that version is from 29.11.2021. What can I do to pinpoint the source of this outdated version?

**Comment by Samandar003** [comment] 2024-08-31 05:52
usr/lib/python3/dist-packages/paramiko/transport.py:220: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):

I ran into this issue while running docker-compose up

**Comment by bskinn** [comment] 2024-09-03 03:37
> `conda list` `paramiko 2.8.1 pyhd3eb1b0_0` `pip list` `paramiko 2.8.1 `
> 
> Seems like that version is from 29.11.2021. What can I do to pinpoint the source of this outdated version?

I poked around; it looks like this is from the main Anaconda package channel. The latest version of paramiko listed is 2.8.1, as of [v2023.03-0][anaconda]. After that version, they don't actually list a version for paramiko; unclear why.

[paramiko on conda-forge][cf], though, has been steadily receiving updates as bitprophet has been releasing them here. If you want to keep using conda, @Eheran1, I suspect your best bet is going to be to switch to pulling it from the conda-forge channel.


[anaconda]: https://docs.anaconda.com/anaconda/allpkglists/2023.03-0/
[cf]: https://anaconda.org/conda-forge/paramiko/files

**Comment by TheMaterialCoder** [comment] 2024-09-30 08:43
Updating paramiko to the latest version v3.5.0 solved the issue for me

> > `conda list` `paramiko 2.8.1 pyhd3eb1b0_0` `pip list` `paramiko 2.8.1 `
> > Seems like that version is from 29.11.2021. What can I do to pinpoint the source of this outdated version?
> 
> I poked around; it looks like this is from the main Anaconda package channel. The latest version of paramiko listed is 2.8.1, as of [v2023.03-0](https://docs.anaconda.com/anaconda/allpkglists/2023.03-0/). After that version, they don't actually list a version for paramiko; unclear why.
> 
> [paramiko on conda-forge](https://anaconda.org/conda-forge/paramiko/files), though, has been steadily receiving updates as bitprophet has been releasing them here. If you want to keep using conda, @Eheran1, I suspect your best bet is going to be to switch to pulling it from the conda-forge channel.

**Comment by eduamf** [comment] 2025-01-25 15:03
Solved doing ...
https://fabianlee.org/2023/03/28/python-fixing-cryptographydeprecationwarning-blowfish-has-been-deprecated/
