### ISSUE TITLE
Paramiko publickey ssh fails when ssh-agent has more than one keys (and right key being not the first one)

### ISSUE THREAD

**Issue by sushilkar** [paramiko/paramiko#1707] opened 2020-06-11 17:15 UTC
In my case:
https://github.com/paramiko/paramiko/blob/dccc563c3a581a14ceaa261b5fe0d08539f84b87/paramiko/client.py#L693

my agent returns lets say 6 keys
```
0 = {AgentKey} <paramiko.agent.AgentKey object at 0x102834334>
1 = {AgentKey} <paramiko.agent.AgentKey object at 0x1028a4390>
2 = {AgentKey} <paramiko.agent.AgentKey object at 0x1028c73c8>
3 = {AgentKey} <paramiko.agent.AgentKey object at 0x1028d6400>
4 = {AgentKey} <paramiko.agent.AgentKey object at 0x1028d5470>
5 = {AgentKey} <paramiko.agent.AgentKey object at 0x1028a64a8>
```

the valid one being #5th one. What I observe is that after submitting first for auth and it fails, the following attempts for publickey auth are not even sent to the SSH server. I could not see anything in the logs/tcpdump at the server end.

```
DEBUG:paramiko.transport:Trying SSH agent key b'xxxxxxxxxxxxxxxxx'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
DEBUG:paramiko.transport:Trying SSH agent key b'xxxxxxxxxxxxxxxxxxx'
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:Trying SSH agent key b'xxxxxxxxxxxxxxxxxxx'
DEBUG:paramiko.transport:Trying SSH agent key b'xxxxxxxxxxxxxxxxxxx'
DEBUG:paramiko.transport:Trying SSH agent key b'xxxxxxxxxxxxxxxxxxx'
DEBUG:paramiko.transport:Trying SSH agent key b'yyyyyyyyyyyyyyyyy' 
``` 
Where yyyyy being the correct public key. 

Sametime, if I can present that in the first yyyyyy, it access and authenticate. I tested reversing(self._agent.get_keys()) tuple.  

Where yyyyy is `ssh-rsa-cert-v01@openssh.com` type key. Actually it was not in the preferred key at all. 
https://github.com/paramiko/paramiko/blob/dccc563c3a581a14ceaa261b5fe0d08539f84b87/paramiko/transport.py#L171-L177
and was getting 
https://github.com/paramiko/paramiko/blob/dccc563c3a581a14ceaa261b5fe0d08539f84b87/paramiko/transport.py#L2355

had to override the transport._preferred_keys and append `ssh-rsa-cert-v01@openssh.com` in order to accept negotiation. As that is the only key type server agreed upon. 

A normal SSH (OS default client, ssh in Linux) client behavior is 
- Offer one after the other until it succeeds or fail to authenticate.
```
debug3: authmethod_is_enabled publickey
13:47:39 debug1: Next authentication method: publickey
13:47:39 debug1: Offering RSA public key: PubkeyONE-RSA
13:47:39 debug3: send_pubkey_test
13:47:39 debug3: send packet: type 50
13:47:39 debug2: we sent a publickey packet, wait for reply
13:47:39 debug3: receive packet: type 51
13:47:39 debug1: Authentications that can continue: publickey
13:47:39 debug1: Offering RSA-CERT public key: 
13:47:39 debug3: send_pubkey_test
13:47:39 debug3: send packet: type 50
13:47:39 debug2: we sent a publickey packet, wait for reply
13:47:39 debug3: receive packet: type 60
13:47:39 debug1: Server accepts key: pkalg ssh-rsa-cert-v01@openssh.com blen 5001
```

**Comment by sushilkar** [comment] 2020-06-11 17:20
https://github.com/paramiko/paramiko/issues/1390 might be same.

**Comment by bitprophet** [comment] 2022-11-04 18:02
What's the server here? I've been unable to replicate this against vanilla OpenSSH servers and #1390 and friends turned out to be specific to Cisco or other "not openssh" endpoints. For now, I'm going to close this as _probably_ a duplicate of that ticket, but happy to reopen if this is a separate issue somehow.

**Closed by bitprophet** 2022-11-04 18:02 UTC
