### ISSUE TITLE
paramiko ssh port forwarding over vpn

### ISSUE THREAD

**Issue by razcore-rad** [paramiko/paramiko#549] opened 2015-06-30 17:11 UTC
Hi, so I've been looking into this `ssh` things lately and discovered the `forward.py` example application. Now, I took it and put it to the test by opening an `ipython` kernel at a remote server and tried connecting to it using `ipython console --existing kernel-1234.py`. I have no problem doing this over ssh, following [the `ipython` example](https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh) **but only if** I forward the ports manually, that is with the little snippet:

```
$ for port in $(cat kernel-1234.json | grep '_port' | grep -o '[0-9]\+'); do
> ssh kerbin -f -N -L $port:127.0.0.1:$port
> done
```

Seeing that I can do this with `ssh` I wanted to try the same thing with the `forward.py` script:

```
$ for port in $(cat kernel-1234.json | grep '_port' | grep -o '[0-9]\+'); do python3 forward.py fionn.ichec.ie -p $port -r fionn.ichec.ie:$port & done
[1] 29114
[2] 29115
[3] 29116
[4] 29117
[5] 29118
$ Connecting to ssh host fionn.ichec.ie:22 ...
Connecting to ssh host fionn.ichec.ie:22 ...
Connecting to ssh host fionn.ichec.ie:22 ...
Connecting to ssh host fionn.ichec.ie:22 ...
Connecting to ssh host fionn.ichec.ie:22 ...
Now forwarding port 36120 to fionn.ichec.ie:36120 ...
Now forwarding port 59998 to fionn.ichec.ie:59998 ...
Now forwarding port 57110 to fionn.ichec.ie:57110 ...
Now forwarding port 53673 to fionn.ichec.ie:53673 ...
Now forwarding port 58202 to fionn.ichec.ie:58202 ...
```

And soon enough (about a minute) I get:

```
Secsh channel 0 open FAILED: Connection timed out: Connect failed
Secsh channel 0 open FAILED: Connection timed out: Connect failed
Incoming request to fionn.ichec.ie:59998 failed: ChannelException(2, 'Connect failed')
Incoming request to fionn.ichec.ie:58202 failed: ChannelException(2, 'Connect failed')
Secsh channel 0 open FAILED: Connection timed out: Connect failed
Secsh channel 0 open FAILED: Connection timed out: Connect failed
Incoming request to fionn.ichec.ie:57110 failed: ChannelException(2, 'Connect failed')
Incoming request to fionn.ichec.ie:36120 failed: ChannelException(2, 'Connect failed')
Secsh channel 1 open FAILED: Connection timed out: Connect failed
etc.
```

Am I doing something wrong here?!...

**Comment by RenaKunisaki** [comment] 2019-06-22 20:06
I'm having the same problem, no VPN:

```
./forward-demo.py -u pi -r localhost:8081 birdhouse
Connecting to ssh host birdhouse:22 ...
Now forwarding port 4000 to localhost:8081 ...
Connected!  Tunnel open ('127.0.0.1', 36428) -> ('fd14:b034:e44f::c7a', 22, 0, 0) -> ('localhost', 8081)
Tunnel closed from ('127.0.0.1', 36428)
Secsh channel 1 open FAILED: Connection refused: Connect failed
Incoming request to localhost:8081 failed: ChannelException(2, 'Connect failed')

Secsh channel 2 open FAILED: Connection refused: Connect failed
```

I can connect and briefly exchange data before the connection drops. Using `ssh -L` works fine.

**Comment by RenaKunisaki** [comment] 2023-03-28 20:51
I never managed to fix it. The machine was destroyed by a power surge.

**Comment by pschroeder89** [comment] 2023-03-28 21:07
Lucky you 😆

Thanks for the reply!

**Comment by bskinn** [comment] 2023-04-28 02:58
The original issue here is almost 8 years old, and the follow on conversation seems closed.

I'm going to close this issue; feel free to reopen or create a new issue if the problem is still relevant.

**Closed by bskinn** 2023-04-28 02:58 UTC
Labels: Needs investigation
