### ISSUE TITLE
[BUG] CryptographyDeprecationWarning: TripleDES has been moved to cryptography

### ISSUE THREAD

**Issue by sunsoftsupport** [paramiko/paramiko#2426] opened 2024-08-03 05:43 UTC
### Are you using paramiko as a client or server?

Server

### What feature(s) aren't working right?

Something else

### What version(s) of paramiko are you using?

3.4.0

### What version(s) of Python are you using?

3.12.3 

### What operating system and version are you using?

Macos Sonoma 14.5

### If you're connecting as a client, which SSH server are you connecting to?

OpenSSH

### Expected/desired behavior

There should not be any working when the program is compiled but I keep getting the warning. Need to update the package so we can run the application without such warning or unintended error

### Actual behavior

venv/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
env/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
venv/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
venv/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Watching for file changes with StatReloader

### How to reproduce

When installed this package and run a python program you will get the warning when running he program.

**Comment by jun66j5** [comment] 2024-08-03 05:59
A duplicate of #2419.

**Closed** 2024-08-03 19:28 UTC
Labels: Bug
