### ISSUE TITLE
ECDSA doesn't work for key sizes other than 256

### ISSUE THREAD

**Issue by CrazyCasta** [paramiko/paramiko#723] opened 2016-04-18 05:25 UTC
As the title explains ECDSA doesn't work for key sizes other than 256 (like 384 and 521). I'm working on a fix for this, so I'm just putting it out at the moment to get things warmed up for my pull request.

P.S. If there's a style document or anything as far as coding guidelines feel free to point me in that direction, otherwise I'm just making a best effort to write good code (follow PEP8, document, etc).

**Comment by CrazyCasta** [comment] 2016-04-18 06:08
Also, I don't know whether to call this a bug or a feature request. On the one hand, for private keys, the current implementation just assumes the key is nistp256 and acts accordingly. This causes the receiving machine to say WTF can't understand nistp256 key (deep in the logs). On the other hand, it also allows for public keys other then nistp256 where in the past it would simply complain that the key format was unsupported.

**Comment by CrazyCasta** [comment] 2016-04-18 20:44
Pull request added: #725

**Comment by bitprophet** [comment] 2016-04-25 01:05
Rolling into the PR (tho I did just close it as a duplicate of #611 :D)

**Closed** 2016-04-25 01:05 UTC
