### ISSUE TITLE
sock._closed not set immediately - race condition when working with threads

### ISSUE THREAD

**Issue by hesekiel** [paramiko/paramiko#782] opened 2016-07-22 05:51 UTC
I noticed a problem when using a transport in this fashion:
1. SSHClient() connection to server A
2. connection.get_transport()
3. transport.open_channel("direct-tcpip", ...)
4. SSHClient() connection to server B using channel from 3. as 'sock' parameter
5. work ...
6. close connection to B
7. close connection to A

During execution of this program I occasionally ( ~ 1/2 of times) get the following exception:
`  File "/usr/local/lib/python3.4/dist-packages/paramiko/client.py", line 394, in close 
    self._transport.close()
  File "/usr/local/lib/python3.4/dist-packages/paramiko/transport.py", line 645, in close 
    self.stop_thread()
  File "/usr/local/lib/python3.4/dist-packages/paramiko/transport.py", line 1550, in stop_thread
    and not self.sock._closed and not self.packetizer.closed
AttributeError: 'Channel' object has no attribute '_closed'
`
This might be due to not immediate change to socket._closed attribute when the socket is closed and than _closed is checked. When I assign `False` manually to this attribute seems to get rid of this problem. Something similar should be done at the declaration of 'sock' variable.

**Comment by bitprophet** [comment] 2016-07-25 19:34
Thanks for the report! Unfortunately this seems to be a duplicate of issue #774. Please make sure to use the search feature in the future :)

**Closed by bitprophet** 2016-07-25 19:34 UTC

**Comment by hesekiel** [comment] 2016-07-26 06:19
I am sorry, I did use the search feature and did not find anything. I should work on my searching skills :) Thank you for redirecting me to the original issue :+1:

**Comment by bitprophet** [comment] 2016-07-26 06:22
@hesekiel No worries. Also, good news, I released the fix to that issue tonight :) check PyPI!
