### ISSUE TITLE
Change banner_timeout time 

### ISSUE THREAD

**Issue by VKen** [paramiko/paramiko#539] opened 2015-06-14 04:38 UTC
I have connected to as SFTP server which is excruciatingly slow, even more than the 15 seconds default setting in `transport.py`

Currently, I have to manually modify the library to extend the time, but running updates will overwrite the changes.

Would be great if there are some ways to set it.

**Comment by bitprophet** [comment] 2015-06-15 20:05
This looks like a dupe of #362 which was released in 1.15.0, so if you nab that version or above it should have an option for setting this. Thanks!

**Closed by bitprophet** 2015-06-15 20:05 UTC

**Comment by VKen** [comment] 2015-06-16 00:27
Thanks for the link to the merge @bitprophet, I found where to set it. Was looking in the `transport.py` file after update, but didn't look into `client.py` earlier.
