### ISSUE TITLE
Authentication successful but can't establish connection

### ISSUE THREAD

**Issue by jidibinlin** [paramiko/paramiko#2119] opened 2022-09-26 12:31 UTC
<img width="627" alt="image" src="https://user-images.githubusercontent.com/38578679/192276720-09c2d5d6-51db-4350-a001-1e408e5db809.png">
Authentication successful but can't establish connection

**Comment by jun66j5** [comment] 2022-09-26 12:44
Please provide the details.

* What version of paramiko are you using?
* What version of installed libraries are you using?
* Provide log with debug level if possible

**Comment by jidibinlin** [comment] 2022-09-26 13:31
+ version
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/38578679/192288659-5c870c26-3a41-4cdf-a855-60183ade7142.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/38578679/192288962-c518cb47-bd54-406a-b5ad-baf8f2376826.png">

I use a for loop to generate 3 ssh client connect to the same host(localhost means I ssh to the server itself 3 times)

**Comment by jun66j5** [comment] 2022-09-26 13:52
P.S. I recommend text rather than image for providing information.

**Comment by jun66j5** [comment] 2022-09-26 13:58
I think that is caused by wrong programming.

Are you storing instances of SSHClient() to a list? Please provide reproduce-able code.

**Comment by jidibinlin** [comment] 2022-09-26 16:32
@jun66j5 Yes I do store instances of sshclient() to a list after the connection established

**Comment by jidibinlin** [comment] 2022-09-26 16:34
Problem only occurred on a this server.

**Comment by jun66j5** [comment] 2022-09-30 20:29
* What is ssh server and version on localhost?
* What is OS name and version on localhost?
* Check log files of the ssh server, syslog and firewall

**Comment by jidibinlin** [comment] 2022-10-01 03:07
@jun66j5 I will check the ssh server version and os version(centos) seven days ago.

**Comment by jidibinlin** [comment] 2022-10-08 09:14
you may take a look at this?
same issue
https://bugzilla.redhat.com/show_bug.cgi

**Comment by jun66j5** [comment] 2022-10-08 09:16
> you may take a look at this? same issue https://bugzilla.redhat.com/show_bug.cgi

Missing bug number.

**Comment by jun66j5** [comment] 2022-10-08 09:21
We cannot search the same issue unless you provide log and stacetrace of the error (especially, log and stacktrace should be _text_).

**Comment by jidibinlin** [comment] 2022-10-08 10:54
Red Hat Bugzilla – Bug 1966593
but number

**Comment by jun66j5** [comment] 2022-10-09 09:14
https://bugzilla.redhat.com/show_bug.cgi?id=1966593 is not the same issue. In the bug 1966593, "authentication successful" is not logged.

You must provide the log of server and client side.

**Comment by jun66j5** [comment] 2022-11-01 01:49
I suggest closing this issue because of no feedback.

**Closed** 2022-11-08 16:23 UTC
Labels: Support
