### ISSUE TITLE
OpenSSH RSA problem

### ISSUE THREAD

**Issue by kuzeyron** [paramiko/paramiko#1363] opened 2019-01-02 16:27 UTC
Hey! I have been searching and searching for a answer.
Have taken me two days without a solution.

I recently moved from Linux Mint to Manjaro. And when I have generated RSA keys, Paramiko is telling me `not a valid RSA private key file`.
And inside the key so the first line is `BEGIN OPENSSH PRIVATE KEY`.
And it doesn't like that. I've asked a few peoples on what their line says. And they get `BEGIN RSA PRIVATE KEY`.

I've tried different ways of `ssh-keygen -b 4096 -t rsa` to try getting the same key as those on Linux Mint.
This problem occurs only with Paramiko and the keys are valid.
Running `ssh-keygen -l -f ~/.ssh/id_rsa` so the first part is `4096 SHA256`

I have also tried using [ed25519](http://docs.paramiko.org/en/2.4/api/keys.html#module-paramiko.ed25519key) from the documentation. But I didn't get that part to work either by using `ssh-keygen -t ed25519`.

I accidently posted on the wrong page but [these guys](https://github.com/iterative/dvc/issues/1187) also wants an answer to this problem!

Any suggestions what to do and how to do it is appreciated!

**Comment by kuzeyron** [comment] 2019-01-02 17:44
One hack that will do for now is to use `openssl req -new -x509 -days 365 -nodes -out cert.pem -keyout cert.pem
`
Remove section `BEGIN CERTIFICATE`
And rename first line to `BEGIN RSA PRIVATE KEY`

**Comment by bitprophet** [comment] 2019-01-03 21:19
Suspect this is a duplicate of #1015 and closing as such - please follow along over there, or comment here if you can confirm I'm seeing things. Thanks!!

**Closed by bitprophet** 2019-01-03 21:19 UTC
