### ISSUE TITLE
Support for %C token

### ISSUE THREAD

**Issue by ritzmann** [paramiko/paramiko#1976] opened 2022-01-20 12:39 UTC
An application using Paramiko was failing for me with the following error message:
`ssh_config percent_expand: unknown key %C`

The cause is this SSH config statement:
```
Host *
    ControlMaster auto
    ControlPath /tmp/ssh-cm-%C
    ControlPersist 30m
```

`%C` is commonly used for the ControlPath nowadays. It would be great if Paramiko could support that.

**Comment by jun66j5** [comment] 2022-01-20 13:01
A duplicate of #852.

**Comment by totaam** [comment] 2022-01-20 13:03
The `ControlPath` feature is one thing (and a duplicate by the looks of things), but not blowing up when `%C` is found would be useful no matter what and is also trivial to add.

**Comment by ritzmann** [comment] 2022-01-20 14:13
Right, this wasn't meant to be about the control functionality but accepting the `%C` token, which may also be used in other configuration contexts.

**Comment by jun66j5** [comment] 2022-01-20 15:04
Sorry. I should check man page before posting the comment.

```
%C    Hash of %l%h%p%r.
```

**Comment by bitprophet** [comment] 2022-02-04 18:51
If tackled together with the actual ControlPath implementation, the latest stab at that seems to be #1931 (which doesn't add support for the actual token either).

But as @jun66j5 notes it's actually just a hash of other connection parameters we already must have handy (local/remote hostnames, port, and cxn username), so - this probably is low-hanging fruit. I don't see an actual PR for this though; if someone makes one & makes sure it includes changelog, doc and test updates, I can try to just-merge it.

**Comment by bitprophet** [comment] 2022-03-11 23:35
This is in now and will be out in 2.10.

**Closed by bitprophet** 2022-03-11 23:35 UTC
