### ISSUE TITLE
sftp.put returns "IOError: Failure" if the destination name is not specified

### ISSUE THREAD

**Issue by XSchelin** [paramiko/paramiko#1000] opened 2017-06-20 15:58 UTC
The specific code snippet:

```
ftp = ssh.open_sftp()
ftp.put("./local_file.sh", "/home/username/")
```

What I expect: The local file is placed in that remote directory.

What I get:

```
Traceback (most recent call last):
  File "filename.py", line 971, in <module>
    ftp.put("./local_file.sh", "/home/username/")
  File "/Library/Python/2.7/site-packages/paramiko/sftp_client.py", line 714, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/Library/Python/2.7/site-packages/paramiko/sftp_client.py", line 670, in putfo
    with self.file(remotepath, 'wb') as fr:
  File "/Library/Python/2.7/site-packages/paramiko/sftp_client.py", line 338, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/Library/Python/2.7/site-packages/paramiko/sftp_client.py", line 767, in _request
    return self._read_response(num)
  File "/Library/Python/2.7/site-packages/paramiko/sftp_client.py", line 819, in _read_response
    self._convert_status(msg)
  File "/Library/Python/2.7/site-packages/paramiko/sftp_client.py", line 852, in _convert_status
    raise IOError(text)
IOError: Failure
```

A great fix would be to allow dropping the file in that directory, to mimic existing `sftp` functionality. A decent fix would be to write a more descriptive error to stdout.

**Comment by abhilashgupta** [comment] 2018-01-24 11:06
Yes, I was stuck at the same error for sometime today.
I was wondering why this isn't possible/fixed already.

**Comment by zmzmdr** [comment] 2018-03-26 09:10
Just specifiy dst file name instead of dir name.  Will fixed.

**Comment by cloviq** [comment] 2018-04-20 19:15
I am experiencing this issue even if I specify a filename. This is really frustrating as it seems to render it impossible to do sftp puts.

**Comment by GPHemsley** [comment] 2018-08-19 15:01
As things stand now, changing this behavior would be somewhat difficult, as `put` simply opens the local file and passes the resulting file object to `putfo`. By the time the error occurs, the original filename has been discarded.

Also, it was and remains documented behavior of `put` that this error could occur:

> Note that the filename should be included. Only specifying a directory may result in an error.

**Comment by GPHemsley** [comment] 2018-08-19 15:55
Wait, that first part may not be true. `putfo` would have access to the `name` attribute of the source file object, so it may be able to do something with it.

**Comment by zachliu** [comment] 2018-09-24 15:39
I have an error `OSError: General failure` that might be related to this
```

**Comment by Suman-Debnath** [comment] 2018-10-16 06:49
I was having the same problem. Got some working solution here[https://stackoverflow.com/questions/3091326/put-in-sftp-using-paramiko](url)
@XSchelin, I have successfully overcome the **IOError: Failure** issue using the following solution:
`ftp = ssh.open_sftp()
ftp.put("./local_file.sh", "/home/username/local_file.sh")`

**Comment by jricardodeleon** [comment] 2019-10-05 03:55
> Just specifiy dst parameter to file name instead of dir name. Will fixed.

As simply as this, Thank you a lot.

**Comment by yasersakkaf** [comment] 2020-10-05 10:00
@zachliu DId you solve the issue?
I am facing the same

**Comment by zachliu** [comment] 2020-10-05 16:06
@yasersakkaf it's been a long time, i forgot what i did :crying_cat_face: 
i'm not having this issue right now using `paramiko 2.7.1`

**Comment by jricardodeleon** [comment] 2020-10-05 17:14
@yasersakkaf  I did solve the issue with the comment above @zmzmdr  March 26, 2018. 'twas long time ago however, as I can see there are more guys that got solved the issue. Just read the comments.

**Comment by yasersakkaf** [comment] 2020-10-06 04:08
Thanks, @zachliu, and @jricardodeleon the issue is solved with the updated version of the library

**Comment by GrandNative** [comment] 2021-12-14 11:39
@fenix849 
Can you explain to me how to solve this problem? How should I use the dst parameter?
I use this syntax:
`sftp.put(save_path, f'/home/ftp/{name}')`
And I got this error:
`OSError: Failure`

I will be very happy to help.

**Comment by rajatgoyal11** [comment] 2023-01-20 11:02
I am using this             

with pysftp.Connection(host=host, username=user, password=passwd) as sftp:
                sftp.put(localpath=tmp_fpath, remotepath="/chhattisgarh_sw/%s" % fname2send, confirm=False)
                sftp.close()

I am getting this error
File "/var/www/apps/env3_7/lib/python3.7/site-packages/paramiko/sftp_client.py", line 898, in _convert_status
raise IOError(text)
OSError: Failure

**Comment by julienvienne** [comment] 2023-07-21 16:29
I had the same issue today, even using absolute paths.
When connecting on SFTP server, please check that on you are really landing in a chroot directory. Some servers are sometime too permissive and let you cd to the upper directory. In such a case, the remote absolute path you think is not. 

```shell
sftp remote.com
sftp> pwd
Remote working directory: /
```

**Comment by dss010101** [comment] 2023-07-31 17:35
this still seems to be not supported.  you need to specify the file names explicitly still, is that correct?

**Comment by bskinn** [comment] 2023-08-15 03:28
Yes, @dss010101, it is best practice to specify the filename for `dst`, not just a directory. The latter _may_ work, but you risk an error.

**Comment by bskinn** [comment] 2023-08-15 03:29
As best I can tell, the original issue here has been addressed, in terms of the guidance to always use a path with the full filename for the destination.

As such, I'm going to close this ticket.

**Closed by bskinn** 2023-08-15 03:29 UTC
